# Generated by Django 3.0.7 on 2020-06-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(null=True)),
                ('developer', models.CharField(max_length=100)),
                ('published_by', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/placeholder.png', upload_to='images/')),
                ('highlighted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-highlighted', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameplatform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GamePlatform'),
        ),
    ]
